[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/assets/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''public, max-age=604800''' 

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/static/*"

  [headers.values]
    # Multi-value headers are expressed with multi-line strings.
	cache-control = '''
	max-age=0,
	no-cache,
	no-store,
	must-revalidate'''
